# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

builds:
  - main: ./cmd/autogun
    id: autogun
    binary: autogun
    goos:
      - linux
      - windows
      - darwin
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/Carbonfrost/autogun/pkg/internal/build.Version={{.Version}}

archives:
  - id: autogun
    builds:
      - autogun
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

brews:
  - name: autogun
    ids:
    - autogun
    repository: 
      owner: Carbonfrost
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    description: "Detect and execute Web browser automation"
    homepage: "https://github.com/Carbonfrost/autogun"

changelog:
  disable: true

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-dev"
