before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/autogun
    id: autogun
    binary: autogun
    goos:
      - linux
      - windows
      - darwin
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/Carbonfrost/autogun/pkg/internal/build.Version={{.Version}}

archives:
  - id: autogun
    builds:
      - autogun
    name_template: "autogun_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      "386": i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip

brews:
  - name: autogun
    ids:
    - autogun
    tap: &tap
      owner: Carbonfrost
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    description: "Detect and execute Web browser automation"
    homepage: "https://github.com/Carbonfrost/autogun"

changelog:
  skip: true

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-dev"
